source 'http://rubygems.org'

gem 'capybara'
gem 'carrierwave'
gem 'css_parser'
gem 'cucumber', '~> 5.1.1'
gem 'faker'
gem 'httparty', '~> 0.18.1'
gem 'json'
gem 'pry'
gem 'rand'
gem 'report_builder', '~> 1.9'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'url_safe_base64', '~> 0.2.2'
gem 'webdrivers'
gem 'twilio-ruby'